version: "3.7"
services:
  postgres:
    container_name: postgres
    restart: always
    build: ./postgres
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - app-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  # api:
  #   container_name: api
  #   restart: always
  #   build: ./api
  #   command: npm start
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ./api:/usr/src/app/
  #     - /usr/src/app/node_modules
  #   depends_on:
  #     - postgres

volumes:
  app-db:
    name: app-db